# Generated by Django 4.0.5 on 2022-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('registration_address', models.TextField()),
                ('bank_details', models.TextField()),
                ('swift', models.CharField(max_length=11)),
                ('account', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('registration_address', models.TextField()),
                ('beneficiary_bank', models.CharField(max_length=255)),
                ('bank_address', models.TextField()),
                ('swift', models.CharField(max_length=11)),
                ('account', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('name', 'inn')},
            },
        ),
    ]
